### ISSUE TITLE
Ferderclient Forge issue

### ISSUE THREAD

**Issue by ferderplays** [ferderplays/FairFunClientz#2]
So i made thee first version of Ferderclient, but when i run it with forge, it don't work, so the Testing Version is a Edited W+2. However, i'm working on fixing the issue

**Comment by absstract** [comment]
writing his own issue 🤦

**Comment by ferderplays** [comment]
yes, cause i wanna inform people about it

**Comment by absstract** [comment]
issues are for people to tell issues about your client not you telling them
